# Generated by Django 4.2 on 2023-04-07 02:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivor',
            name='name',
            field=models.CharField(blank=True, help_text='Survivor Name', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Name'),
        ),
    ]
