# Generated by Django 4.2 on 2023-04-07 04:08

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_survivor_managers_remove_survivor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='nickname',
            field=models.CharField(blank=True, help_text='Survivor Name', max_length=50, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
