# Generated by Django 4.2 on 2023-04-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_survivor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
